### ISSUE TITLE
Criar layout para placa

### ISSUE THREAD

**Issue by JonathanRufino** [NotifiCar/NotifiCar.Android#17]
Criar um layout (xml) com formato de placa para ser aplicado na lista de placas

Exemplo:
![account](https://cloud.githubusercontent.com/assets/5273493/25601421/5b21e898-2ec2-11e7-8083-0df575f36fba.png)

**Comment by luishng** [comment]
Adicione um novo arquivo xml na pasta drawable com o seguinte código: 

```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle" >

    <solid android:color="#ffffff" />

    <stroke
        android:width="5dp"
        android:color="#686868" />

    <corners
        android:radius="10dp" />

</shape>
```

**Os pontos brancos em cima da placa como na imagem, não foi possível ser feito.**
